### ISSUE TITLE
Examples: Error: No ESLint configuration found

### ISSUE THREAD

**Issue by hifall** [apexcharts/vue-apexcharts#19]
When I do `npm run serve`, I get:

```
npm run serve

> example@0.1.0 serve /Projects/vue-apexcharts/example
> vue-cli-service serve

 INFO  Starting development server...
 94% after seal                                                               -         
 ERROR  Failed to compile with 1 errors                                 16:59:40

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/Projects/vue-apexcharts/example/node_modules/eslint/lib/config.js:255:39)
    at Config.getConfigHierarchy (/Projects/vue-apexcharts/example/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/Projects/vue-apexcharts/example/node_modules/eslint/lib/config.js:286:21)
    at Config.getConfig (/Projects/vue-apexcharts/example/node_modules/eslint/lib/config.js:329:29)
    at processText (/Projects/vue-apexcharts/example/node_modules/eslint/lib/cli-engine.js:163:33)
    at CLIEngine.executeOnText (/Projects/vue-apexcharts/example/node_modules/eslint/lib/cli-engine.js:620:17)
    at lint (/Projects/vue-apexcharts/example/node_modules/eslint-loader/index.js:237:17)
    at transform (/Projects/vue-apexcharts/example/node_modules/eslint-loader/index.js:215:18)
    at /Projects/vue-apexcharts/example/node_modules/loader-fs-cache/index.js:127:18
    at ReadFileContext.callback (/Projects/vue-apexcharts/example/node_modules/loader-fs-cache/index.js:31:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
```

Idea? Thanks!

**Comment by junedchhipa** [comment]
Try creating a file named `.eslintrc.js` in the root of examples directory and input something in the file 
```
{
    "rules": {
        "semi": ["error", "always"],
        "quotes": ["error", "double"]
    }
}
```

**Comment by vikas-ukani** [comment]
> Try creating a file named `.eslintrc.json` in the root of examples directory and input something in the file
> 
> ```
> {
>     "rules": {
>         "semi": ["error", "always"],
>         "quotes": ["error", "double"]
>     }
> }
> ```

It's working in my case.

Thanks for the help @junedchhipa

**Comment by Madni-Pothiyawala** [comment]
> Try creating a file named `.eslintrc.json` in the root of examples directory and input something in the file
> 
> ```
> {
>     "rules": {
>         "semi": ["error", "always"],
>         "quotes": ["error", "double"]
>     }
> }
> ```

It's not working for me.

Is there another way ?
